Import libraries

In [3]:
import pandas as pd
import numpy as np
#preprocessing tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.utils import resample
#classification models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
#for model evaluation
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

Load dataset

In [4]:
df=pd.read_csv("C:/Users/Admin/Downloads/student-scores.csv")
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [5]:
df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

Data cleaning and preprocessing

In [6]:
#drop columns
df.drop(columns=['id', 'first_name', 'last_name', 'email'],inplace=True)
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [7]:
df.isnull().sum()

gender                        0
part_time_job                 0
absence_days                  0
extracurricular_activities    0
weekly_self_study_hours       0
career_aspiration             0
math_score                    0
history_score                 0
physics_score                 0
chemistry_score               0
biology_score                 0
english_score                 0
geography_score               0
dtype: int64

Create new feature

In [8]:
df['total_score']=df['math_score']+df[ 'history_score']+df[ 'physics_score']+df['chemistry_score']+df[ 'biology_score']+df[ 'english_score']+df[ 'geography_score']
df.columns

Index(['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score', 'total_score'],
      dtype='object')

Encoding

In [9]:
encoder=LabelEncoder()
df['gender']=encoder.fit_transform(df['gender'])
df['part_time_job']=encoder.fit_transform(df['part_time_job'])
df['extracurricular_activities']=encoder.fit_transform(df['extracurricular_activities'])
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score
0,1,0,3,0,27,Lawyer,73,81,93,97,63,80,87,574
1,0,0,2,0,47,Doctor,90,86,96,100,90,88,90,640
2,0,0,9,1,13,Government Officer,81,97,95,96,65,77,94,605
3,0,0,5,0,3,Artist,71,74,88,80,89,63,86,551
4,1,0,5,0,10,Unknown,84,77,65,65,80,74,76,521

In [10]:
df['career_aspiration'].values

array(['Lawyer', 'Doctor', 'Government Officer', ..., 'Software Engineer',
       'Business Owner', 'Accountant'], dtype=object)

In [11]:
df['career_aspiration'].dtype

dtype('O')

In [12]:
career_map = {
    'Lawyer': 0,
    'Doctor': 1,
    'Government Officer': 2,
    'Artist': 3,
    'Unknown': 4,
    'Software Engineer': 5,
    'Teacher': 6,
    'Business Owner': 7,
    'Banker': 8,
    'Accountant': 9,
    'Real Estate Developer': 10,
    'Stock Investor': 11,
    'Construction Engineer': 12,
    'Game Developer': 13,
    'Designer': 14,
    'Scientist': 15,
    'Writer': 16
}

df['career_aspiration'] = df['career_aspiration'].map(career_map)
df['career_aspiration'].isna().sum()

0

In [13]:
df.head(10)

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score
0,1,0,3,0,27,0,73,81,93,97,63,80,87,574
1,0,0,2,0,47,1,90,86,96,100,90,88,90,640
2,0,0,9,1,13,2,81,97,95,96,65,77,94,605
3,0,0,5,0,3,3,71,74,88,80,89,63,86,551
4,1,0,5,0,10,4,84,77,65,65,80,74,76,521
5,0,0,2,0,26,4,93,100,67,78,72,80,84,574
6,1,0,3,1,23,5,99,96,97,73,88,76,64,593
7,1,1,2,1,34,5,95,95,82,63,84,70,85,574
8,1,0,6,0,25,4,94,68,94,85,81,74,72,568
9,0,0,3,1,18,6,98,69,88,71,67,71,73,537

In [14]:
df.columns

Index(['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score', 'total_score'],
      dtype='object')

Scaling:Normalization

In [15]:
# Define the columns to scale
scale_cols = ['absence_days', 'weekly_self_study_hours', 'math_score', 'history_score',
              'physics_score', 'chemistry_score', 'biology_score',
              'english_score', 'geography_score']

scaler = StandardScaler()

df[scale_cols] = scaler.fit_transform(df[scale_cols])
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score
0,1,0,-0.253175,0,0.762334,0,-0.790525,0.052463,0.930377,1.331147,-1.208673,-0.106245,0.525321,574
1,0,0,-0.633604,0,2.411605,1,0.495250,0.445147,1.169682,1.565986,0.759435,0.559086,0.783168,640
2,0,0,2.029397,1,-0.392155,2,-0.185454,1.309054,1.089913,1.252867,-1.062888,-0.355744,1.126964,605
3,0,0,0.507682,0,-1.216791,3,-0.941792,-0.497296,0.531536,0.000391,0.686542,-1.520075,0.439372,551
4,1,0,0.507682,0,-0.639546,4,0.041447,-0.261685,-1.303134,-1.173804,0.030506,-0.605244,-0.420119,521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,0,-0.633604,0,1.009725,12,-0.034186,-0.261685,0.212463,-0.547567,-0.333959,0.226421,0.095575,558
1996,1,0,-0.633604,0,0.185089,5,0.419616,-1.204128,-0.664988,0.000391,0.540756,-1.187409,-0.677966,534
1997,0,0,0.507682,0,-0.309692,5,1.024687,0.366610,-1.462670,1.018028,-0.844209,1.058085,-0.248221,578
1998,0,1,2.409825,1,-1.051864,7,-2.454469,1.230517,-0.744756,0.704909,1.123899,0.559086,-0.506068,566
1999,0,0,0.507682,0,0.762334,9,-0.109820,1.466128,0.770840,-0.860686,0.249184,0.974919,1.642659,617

Data Balancing

In [16]:
df['career_aspiration'].value_counts()

career_aspiration
5     315
7     309
4     223
8     169
0     138
9     126
1     119
10     83
11     73
12     68
3      67
13     63
2      61
6      59
14     56
15     39
16     32
Name: count, dtype: int64

In [17]:
# Split the dataframe into separate DataFrames for each class
classes = df['career_aspiration'].unique()
df_list = [df[df['career_aspiration'] == label] for label in classes]

# Find the class with the maximum count
max_size = max([len(sub_df) for sub_df in df_list])

# Resample each class to match the max_size
df_upsampled = [resample(sub_df,
                         replace=True,      # sample with replacement
                         n_samples=max_size, # to match majority class
                         random_state=42)    # reproducible results
                for sub_df in df_list]

# Combine back into a single DataFrame
df = pd.concat(df_upsampled)

# Shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df['career_aspiration'].value_counts()

career_aspiration
11    315
2     315
4     315
7     315
13    315
8     315
15    315
14    315
3     315
5     315
9     315
10    315
16    315
0     315
12    315
1     315
6     315
Name: count, dtype: int64

In [18]:
classes=df['career_aspiration'].unique()
df_list=[df[df['career_aspiration']==label]for label in classes]
df_list

[      gender  part_time_job  absence_days  extracurricular_activities  \
 0          0              0      0.507682                           0
 12         1              0     -0.633604                           0
 34         1              0     -1.014033                           0
 52         1              1     -0.253175                           0
 54         0              1      0.127253                           1
 ...      ...            ...           ...                         ...
 5270       0              0     -1.394461                           0
 5272       1              0     -1.014033                           0
 5281       1              0      0.127253                           0
 5286       1              0     -1.014033                           0
 5332       0              0     -0.633604                           1

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 0                    0.844798                 11    0.343983       0.759295
 12                   1.092188                 11    1.175955       0.602221
 34                   0.102626                 11    0.570884       0.680758
 52                  -0.474619                 11    0.041447      -0.889981
 54                   0.514944                 11    0.192715      -0.968518
 ...                       ...                ...         ...            ...
 5270                -1.134327                 11    0.192715       0.131000
 5272                 0.927261                 11   -0.261088       1.230517
 5281                -0.474619                 11    1.251588      -1.047054
 5286                 0.597407                 11    0.117081       0.131000
 5332                 1.174652                 11   -0.639257       0.209537

       physics_score  chemistry_score  biology_score  english_score  \
 0          0.930377         0.078671       0.613649       0.725419
 12         1.249450         1.331147      -0.625530      -1.187409
 34        -1.223366        -0.860686       1.488363       0.559086
 52        -1.063829         0.939748       0.467863      -1.187409
 54         1.329218         0.548349      -1.354459      -0.272578
 ...             ...              ...            ...            ...
 5270       0.691072        -0.860686      -0.989995       0.974919
 5272      -0.186378         1.174587      -0.406852       1.141252
 5281       1.488755        -1.565203       1.051006      -0.771577
 5286       0.531536        -1.408644      -0.625530      -0.854743
 5332       0.292231        -1.173804      -0.261066       1.058085

       geography_score  total_score
 0           -0.592017          604
 12          -0.162272          598
 34          -0.162272          582
 52          -0.677966          539
 54           1.298863          574
 ...               ...          ...
 5270         1.126964          580
 5272        -1.709355          580
 5281        -0.935814          563
 5286        -0.506068          534
 5332        -1.795305          538

 [315 rows x 14 columns],
       gender  part_time_job  absence_days  extracurricular_activities  \
 1          0              0      0.507682                           0
 4          1              1     -0.253175                           0
 44         1              0      1.268539                           0
 65         0              0     -0.633604                           0
 82         0              0     -0.633604                           1
 ...      ...            ...           ...                         ...
 5225       1              0     -0.633604                           0
 5226       1              0     -0.633604                           0
 5295       1              0     -0.253175                           0
 5324       1              0     -0.633604                           0
 5342       0              0     -0.253175                           0

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 1                    1.257115                  5    0.192715      -1.439739
 4                   -0.227228                  5    1.251588       0.759295
 44                   1.257115                  5    1.175955      -1.518276
 65                   0.185089                  5    0.117081       1.544665
 82                   0.927261                  5    0.343983       0.209537
 ...                       ...                ...         ...            ...
 5225                 0.102626                  5    0.873419       0.916369
 5226                 1.339579                  5    0.722152      -1.204128
 5295                 0.679871                  5    0.192715      -1.361202
 5324                 1.092188                  5    0.117081      -0.340222
 5342                -0.144765                  5    0.570884       0.288073

       physics_score  chemistry_score  biology_score  english_score  \
 1         -0.026842        -1.330364      -0.333959       0.891752
 4         -0.744756         1.409426      -0.479745       1.307584
 44        -0.505451        -0.938965      -0.989995       0.725419
 65        -1.382902        -0.938965      -0.479745      -0.023079
 82         1.010145         0.000391       1.269685       1.141252
 ...             ...              ...            ...            ...
 5225      -0.664988         1.096307      -0.479745      -0.937910
 5226      -0.026842         1.096307       0.905220      -1.769574
 5295      -0.266147        -0.156168       0.030506      -1.187409
 5324       0.052926         0.391790      -0.479745      -1.769574
 5342       1.089913         1.331147       0.613649      -0.937910

       geography_score  total_score
 1            1.212914          554
 4           -0.763915          602
 44           1.556710          558
 65           0.525321          558
 82          -0.248221          615
 ...               ...          ...
 5225         1.126964          591
 5226         1.642659          585
 5295         1.384812          549
 5324         0.783168          551
 5342        -0.334170          602

 [315 rows x 14 columns],
       gender  part_time_job  absence_days  extracurricular_activities  \
 2          1              0      0.127253                           0
 49         1              0      0.888111                           0
 58         0              0      0.507682                           0
 61         1              0      0.127253                           0
 64         1              1     -1.014033                           0
 ...      ...            ...           ...                         ...
 5269       0              0      0.507682                           0
 5275       0              0      0.507682                           0
 5310       1              0     -0.253175                           0
 5330       1              0     -0.253175                           0
 5349       0              0      0.888111                           0

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 2                    1.916824                  1    0.797785       1.073443
 49                   1.339579                  1    0.797785       0.209537
 58                   0.350017                  1    0.646518       0.445147
 61                   1.257115                  1    0.797785      -0.497296
 64                   2.329142                  1    0.949053       0.366610
 ...                       ...                ...         ...            ...
 5269                 2.081751                  1    0.495250       1.230517
 5275                 0.679871                  1    0.495250       0.916369
 5310                 2.329142                  1    0.949053       0.680758
 5330                 1.999287                  1    0.419616       0.759295
 5349                 2.494069                  1    0.873419       0.759295

       physics_score  chemistry_score  biology_score  english_score  \
 2          1.010145         0.704909       0.394970       0.392754
 49         1.408986         1.565986       1.051006       0.808586
 58         0.451767         0.078671       0.978113       0.725419
 61         1.089913         0.156951       1.488363      -1.520075
 64         0.691072         1.174587       1.488363       1.224418
 ...             ...              ...            ...            ...
 5269       1.488755         0.548349       1.488363       0.725419
 5275       1.089913         0.391790       0.978113      -1.021076
 5310       0.770840         0.783189       0.759435       0.808586
 5330       0.770840         1.174587       0.540756       0.891752
 5349       0.292231         0.783189       1.196792       0.642253

       geography_score  total_score
 2            0.353423          627
 49          -1.021763          630
 58           1.556710          628
 61           1.384812          605
 64           0.611270          650
 ...               ...          ...
 5269         0.697219          652
 5275        -1.365559          589
 5310         1.556710          646
 5330         1.298863          640
 5349         1.298863          641

 [315 rows x 14 columns],
       gender  part_time_job  absence_days  extracurricular_activities  \
 3          1              0     -0.633604                           0
 10         1              0     -0.253175                           0
 28         1              0      2.409825                           0
 33         1              0      0.888111                           0
 43         1              0     -0.253175                           1
 ...      ...            ...           ...                         ...
 5164       1              0      1.268539                           1
 5175       1              1      0.888111                           0
 5227       1              0     -1.014033                           0
 5284       1              0     -0.633604                           0
 5333       1              0     -0.633604                           0

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 3                    0.267553                 12   -0.034186       0.052463
 10                   1.422043                 12    0.117081       0.759295
 28                  -0.557082                 12    1.251588      -1.596813
 33                   1.422043                 12    0.495250       0.445147
 43                   0.020162                 12    1.100321      -1.047054
 ...                       ...                ...         ...            ...
 5164                -0.557082                 12    1.024687       0.837832
 5175                -0.227228                 12    0.495250      -0.732907
 5227                 1.339579                 12   -0.034186      -1.596813
 5284                 1.422043                 12    0.949053       0.759295
 5333                -0.227228                 12    0.646518      -1.361202

       physics_score  chemistry_score  biology_score  english_score  \
 3          1.169682        -1.408644      -0.989995       0.725419
 10         1.169682         1.174587       1.123899       0.559086
 28         0.451767        -1.565203       0.467863       0.974919
 33         1.408986         1.096307       1.488363       0.642253
 43        -0.106610        -0.938965       0.030506       0.559086
 ...             ...              ...            ...            ...
 5164       0.770840        -1.486923      -0.844209      -0.355744
 5175       0.930377        -0.547567       0.030506      -0.272578
 5227      -0.106610         0.939748       0.322077      -1.769574
 5284       0.770840         1.174587       1.415471       1.141252
 5333       0.770840        -1.173804      -0.771316       1.058085

       geography_score  total_score
 3            0.869117          569
 10           0.783168          639
 28          -0.506068          561
 33           0.353423          643
 43           0.353423          566
 ...               ...          ...
 5164         1.384812          582
 5175        -1.021763          554
 5227        -0.935814          529
 5284         1.556710          665
 5333         1.470761          572

 [315 rows x 14 columns],
       gender  part_time_job  absence_days  extracurricular_activities  \
 5          1              0     -1.014033                           0
 6          0              0      0.507682                           0
 37         0              0      2.029397                           0
 45         0              0      0.888111                           1
 62         1              0     -0.253175                           0
 ...      ...            ...           ...                         ...
 5285       1              0     -1.014033                           0
 5298       1              0     -1.014033                           0
 5307       0              0      0.507682                           0
 5323       1              0     -1.394461                           0
 5343       0              0      0.888111                           1

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 5                    1.174652                  0    1.251588       0.680758
 6                    0.844798                  0    0.117081       1.466128
 37                   0.679871                  0   -0.563623       0.209537
 45                   1.174652                  0   -0.412356       0.916369
 62                   1.422043                  0    0.495250       0.602221
 ...                       ...                ...         ...            ...
 5285                 1.257115                  0    0.192715       0.445147
 5298                 0.844798                  0   -0.866158       0.994906
 5307                 1.257115                  0   -0.034186       0.445147
 5323                 1.339579                  0    0.646518       0.759295
 5343                 1.174652                  0   -0.412356       0.916369

       physics_score  chemistry_score  biology_score  english_score  \
 5          1.089913        -1.330364      -0.917102       0.891752
 6         -1.382902        -0.156168      -1.208673       1.141252
 37         0.691072        -0.938965       1.196792       1.058085
 45        -0.345915         1.565986      -1.354459       0.060088
 62         1.010145         1.487706       0.905220       0.475920
 ...             ...              ...            ...            ...
 5285      -1.382902        -1.486923       1.269685       1.307584
 5298      -1.063829        -1.408644       0.249184       1.390751
 5307      -1.622207         1.487706       1.415471       0.559086
 5323      -1.303134        -0.077888       1.196792       0.475920
 5343      -0.345915         1.565986      -1.354459       0.060088

       geography_score  total_score
 5           -0.506068          581
 6            0.869117          575
 37           0.525321          594
 45          -1.709355          551
 62           1.384812          647
 ...               ...          ...
 5285         0.869117          582
 5298        -1.193661          543
 5307        -0.677966          589
 5323        -0.592017          583
 5343        -1.709355          551

 [315 rows x 14 columns],
       gender  part_time_job  absence_days  extracurricular_activities  \
 7          1              0      0.127253                           0
 9          1              0      0.507682                           0
 11         0              0     -0.633604                           1
 21         1              0     -1.014033                           0
 63         1              0      1.268539                           0
 ...      ...            ...           ...                         ...
 5297       0              0     -0.253175                           0
 5316       0              0     -0.253175                           1
 5334       1              0     -0.633604                           0
 5345       0              0      0.888111                           0
 5346       0              1     -0.253175                           0

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 7                    0.762334                 16   -0.261088      -0.340222
 9                    0.927261                 16   -0.563623       0.523684
 11                  -0.144765                 16   -0.941792       1.544665
 21                   0.020162                 16   -0.034186       1.230517
 63                   0.432480                 16   -1.017426       0.837832
 ...                       ...                ...         ...            ...
 5297                -0.309692                 16    0.419616      -0.575833
 5316                 0.267553                 16   -1.093060      -0.261685
 5334                -0.144765                 16   -1.017426      -0.418759
 5345                 1.339579                 16    0.570884      -0.418759
 5346                 0.350017                 16   -1.622497       0.523684

       physics_score  chemistry_score  biology_score  english_score  \
 7         -0.824524        -1.408644       0.905220       1.473917
 9         -1.382902        -0.469287      -0.479745       0.725419
 11         1.408986         1.174587       0.832327       1.224418
 21        -0.744756         0.078671       0.467863       0.974919
 63        -0.026842        -1.486923      -1.135781       0.974919
 ...             ...              ...            ...            ...
 5297       1.169682         0.313510       1.196792       1.390751
 5316       0.052926         1.018028       0.905220       0.725419
 5334      -0.186378        -0.234448      -1.062888       0.891752
 5345       0.052926        -0.938965       0.613649       1.390751
 5346       0.930377         0.235231       0.978113       1.307584

       geography_score  total_score
 7           -0.334170          557
 9            1.556710          563
 11           1.298863          648
 21          -0.506068          586
 63           1.298863          556
 ...               ...          ...
 5297        -0.334170          613
 5316        -0.849865          574
 5334        -0.248221          536
 5345         0.611270          590
 5346        -0.677966          588

 [315 rows x 14 columns],
       gender  part_time_job  absence_days  extracurricular_activities  \
 8          1              0     -0.253175                           0
 32         0              0      0.888111                           0
 40         1              0     -0.253175                           0
 46         1              0      1.268539                           0
 68         0              0      0.507682                           1
 ...      ...            ...           ...                         ...
 5337       0              0     -0.633604                           0
 5338       1              0     -0.253175                           0
 5348       1              0     -0.253175                           0
 5352       1              0     -0.253175                           0
 5353       1              0     -0.633604                           0

       weekly_self_study_hours  career_aspiration  math_score  history_score  \
 8                   -1.464181                 10   -0.639257      -1.125591
 32                  -0.804473                 10   -0.185454      -1.047054
 40                  -1.381718                 10   -2.151933       0.052463
 46                  -1.051864                 10   -2.000666      -0.497296
 68                  -1.216791                 10   -1.546863      -0.261685
 ...                       ...                ...         ...            ...
 5337                -1.216791                 10   -1.925032      -1.125591
 5338                -1.299254                 10    1.175955      -0.340222

Train Test Split

In [19]:
X=df.drop('career_aspiration',axis=1)
y=df['career_aspiration']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("Train shape:",X_train.shape)
print("Test shape:",X_test.shape)

Train shape: (4284, 13)
Test shape: (1071, 13)

Training ,Testing Multiple Classifiers

In [20]:
# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)

==================================================
Model: Logistic Regression

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 0.4024276377217554
Classification Report:
               precision    recall  f1-score   support

           0       0.39      0.41      0.40        74
           1       0.45      0.48      0.47        71
           2       0.38      0.27      0.32        67
           3       0.41      0.47      0.44        68
           4       0.23      0.09      0.13        75
           5       0.18      0.23      0.20        48
           6       0.48      0.77      0.59        57
           7       0.58      0.82      0.68        51
           8       0.27      0.13      0.18        60
           9       0.42      0.46      0.44        61
          10       0.31      0.25      0.28        64
          11       0.38      0.16      0.22        57
          12       0.41      0.48      0.44        62
          13       0.57      0.82      0.67        68
          14       0.15      0.07      0.10        70
          15       0.36      0.42      0.39        62
          16       0.39      0.62      0.48        56

    accuracy                           0.40      1071
   macro avg       0.37      0.41      0.38      1071
weighted avg       0.37      0.40      0.37      1071

Confusion Matrix:
 [[30  2  0  0  2  6  0  0  3  3  0  0  4  0  1  6 17]
 [12 34  0  0  0  5  0  0  1  0  0  0  4  0  0 14  1]
 [ 0  0 18  4  4  2 11  5  0  4  5  1  1  2  6  0  4]
 [ 0  0  5 32  0  0  5  1  0  0 15  0  0 10  0  0  0]
 [ 1  4  4  4  7  4  6  3  5 10  3  1  4  6  4  4  5]
 [ 3  0  0  0  0 11  1  0  9  6  0  6  4  0  1  4  3]
 [ 0  0  2  0  0  1 44  5  0  0  0  0  0  2  3  0  0]
 [ 0  0  0  5  0  0  0 42  0  0  3  0  0  1  0  0  0]
 [ 5  0  0  0  7  9  6  0  8  3  0  3  5  0  4  4  6]
 [ 3  0  0  0  3  5  1  2  1 28  0  2  5  0  4  5  2]
 [ 0  0  7 17  0  0  4  5  0  0 16  0  0 14  1  0  0]
 [ 2  6  4  0  2  3  1  4  1  8  4  9  7  1  2  1  2]
 [ 8  4  0  0  2  7  0  0  0  4  0  2 30  0  2  1  2]
 [ 0  0  0  8  0  0  1  3  0  0  0  0  0 56  0  0  0]
 [ 2  4  7  8  3  7  8  3  2  0  5  0  5  4  5  3  4]
 [ 3 20  0  0  0  0  0  0  0  0  0  0  4  0  0 26  9]
 [ 8  1  0  0  1  0  3  0  0  0  0  0  1  2  1  4 35]]
==================================================
Model: Support Vector Classifier

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Accuracy: 0.13445378151260504
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        74
           1       0.30      0.76      0.43        71
           2       0.00      0.00      0.00        67
           3       0.00      0.00      0.00        68
           4       0.00      0.00      0.00        75
           5       0.05      0.46      0.09        48
           6       0.12      0.16      0.14        57
           7       0.22      0.65      0.33        51
           8       0.00      0.00      0.00        60
           9       0.11      0.18      0.14        61
          10       0.00      0.00      0.00        64
          11       0.00      0.00      0.00        57
          12       0.00      0.00      0.00        62
          13       0.00      0.00      0.00        68
          14       0.00      0.00      0.00        70
          15       0.12      0.24      0.16        62
          16       0.00      0.00      0.00        56

    accuracy                           0.13      1071
   macro avg       0.05      0.14      0.08      1071
weighted avg       0.05      0.13      0.07      1071

Confusion Matrix:
 [[ 0 16  0  0  0 28  5  2  0  5  0  0  0  0  0 11  7]
 [ 0 54  0  0  0  6  1  0  0  0  0  0  0  0  0 10  0]
 [ 0  6  0  0  0 26  7 18  0  3  0  0  0  0  0  6  1]
 [ 0  6  0  0  0 25  7  5  0 15  0  0  0  0  0  9  1]
 [ 0  5  0  0  0 33  5 17  0  9  0  0  0  0  0  5  1]
 [ 0  6  0  0  0 22  3  3  0  7  0  0  0  0  0  7  0]
 [ 0  5  0  0  0 25  9 10  0  5  0  0  0  0  0  3  0]
 [ 0  1  0  0  0  5  5 33  0  7  0  0  0  0  0  0  0]
 [ 0  6  0  0  0 37  2  4  0  4  0  0  0  0  0  6  1]
 [ 0  8  0  0  0 17  2 18  0 11  0  0  0  0  0  5  0]
 [ 0  2  0  0  0 31  5 12  0  9  0  0  0  0  0  5  0]
 [ 0  3  0  0  0 19  2  9  0  9  0  0  0  0  0 15  0]
 [ 0 12  0  0  0 33  5  5  0  0  0  0  0  0  0  6  1]
 [ 0  6  0  0  0 37  8  6  0  5  0  0  0  0  0  6  0]
 [ 0 13  0  0  0 41  4  5  0  3  0  0  0  0  0  3  1]
 [ 0 26  0  0  0 18  0  0  0  2  0  0  0  0  0 15  1]
 [ 0  8  0  0  0 28  4  2  0  3  0  0  0  0  0 11  0]]
==================================================
Model: Random Forest Classifier
Accuracy: 0.9299719887955182
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94        74
           1       0.96      0.92      0.94        71
           2       0.94      0.99      0.96        67
           3       0.86      1.00      0.93        68
           4       0.86      0.76      0.81        75
           5       0.81      0.73      0.77        48
           6       0.92      1.00      0.96        57
           7       0.94      0.96      0.95        51
           8       0.85      0.77      0.81        60
           9       1.00      0.95      0.97        61
          10       0.97      0.88      0.92        64
          11       0.95      0.96      0.96        57
          12       0.90      1.00      0.95        62
          13       0.98      0.96      0.97        68
          14       1.00      0.97      0.99        70
          15       0.98      0.98      0.98        62
          16       0.95      1.00      0.97        56

    accuracy                           0.93      1071
   macro avg       0.93      0.93      0.93      1071
weighted avg       0.93      0.93      0.93      1071

Confusion Matrix:
 [[72  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 1 65  0  0  0  1  0  0  1  0  0  0  2  0  0  1  0]
 [ 0  0 66  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0 68  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  3 57  4  1  1  3  0  1  0  2  0  0  0  2]
 [ 1  1  0  0  3 35  1  0  4  0  0  1  2  0  0  0  0]
 [ 0  0  0  0  0  0 57  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 49  0  0  0  0  0  1  0  0  0]
 [ 5  2  1  0  2  1  3  0 46  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2  0  0  0 58  0  0  0  0  0  0  0]
 [ 0  0  2  4  0  0  0  2  0  0 56  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0 65  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0 68  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56]]
==================================================
Model: K Nearest Neighbors
Accuracy: 0.6984126984126984
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.58      0.63        74
           1       0.69      0.73      0.71        71
           2       0.73      0.76      0.74        67
           3       0.67      0.85      0.75        68
           4       0.38      0.28      0.32        75
           5       0.41      0.35      0.38        48
           6       0.74      0.95      0.83        57
           7       0.90      0.51      0.65        51
           8       0.60      0.43      0.50        60
           9       0.64      0.52      0.58        61
          10       0.68      0.62      0.65        64
          11       0.68      0.74      0.71        57
          12       0.73      0.85      0.79        62
          13       0.85      0.81      0.83        68
          14       0.69      0.87      0.77        70
          15       0.85      0.98      0.91        62
          16       0.85      1.00      0.92        56

    accuracy                           0.70      1071
   macro avg       0.69      0.70      0.69      1071
weighted avg       0.69      0.70      0.69      1071

Confusion Matrix:
 [[43  7  0  0  0  6  1  0  0  0  1  9  1  0  1  3  2]
 [ 5 52  0  0  2  1  0  0  1  1  0  0  3  0  0  5  1]
 [ 0  0 51  5  0  0  2  0  0  0  1  1  1  3  2  1  0]
 [ 0  0  0 58  1  1  1  0  0  0  2  1  0  0  4  0  0]
 [ 3  5  4  3 21  6  6  1  7  5  2  1  2  0  6  0  3]
 [ 4  1  2  0  5 17  1  0  4  5  2  1  2  1  1  1  1]
 [ 2  0  0  1  0  0 54  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  5  1  2 26  0  1  7  0  0  0  2  0  0]
 [ 5  4  0  2  8  2  1  1 26  1  2  1  3  0  1  1  2]
 [ 0  4  4  0  3  4  3  1  1 32  0  2  1  2  4  0  0]
 [ 0  1  6  6  1  0  1  0  0  4 40  0  4  0  1  0  0]
 [ 0  0  0  2  5  2  0  0  1  0  1 42  0  0  3  0  1]
 [ 0  0  0  0  2  1  1  0  0  0  1  1 53  2  1  0  0]
 [ 0  0  3  3  0  0  0  0  3  1  0  1  2 55  0  0  0]
 [ 0  1  0  0  3  0  0  0  0  0  0  2  1  2 61  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56]]
==================================================
Model: Decision Tree Classifier
Accuracy: 0.9187675070028011
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.92      0.89        74
           1       0.97      0.94      0.96        71
           2       0.93      0.99      0.96        67
           3       0.86      1.00      0.93        68
           4       0.84      0.72      0.78        75
           5       0.87      0.71      0.78        48
           6       0.95      1.00      0.97        57
           7       0.94      0.86      0.90        51
           8       0.90      0.72      0.80        60
           9       0.95      0.95      0.95        61
          10       0.92      0.92      0.92        64
          11       0.86      0.96      0.91        57
          12       0.91      1.00      0.95        62
          13       1.00      0.94      0.97        68
          14       0.92      0.97      0.94        70
          15       0.98      0.98      0.98        62
          16       0.97      1.00      0.98        56

    accuracy                           0.92      1071
   macro avg       0.92      0.92      0.92      1071
weighted avg       0.92      0.92      0.92      1071

Confusion Matrix:
 [[68  0  0  0  1  1  0  0  0  0  0  3  0  0  0  0  1]
 [ 0 67  0  0  2  1  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0 66  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0 68  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  2  4  1 54  2  0  3  3  0  1  0  2  0  0  0  0]
 [ 1  0  0  0  3 34  0  0  2  3  0  2  2  0  1  0  0]
 [ 0  0  0  0  0  0 57  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0 44  0  0  3  0  0  0  1  0  0]
 [ 7  0  0  0  3  0  3  0 43  0  0  1  0  0  1  1  1]
 [ 0  0  0  0  1  1  0  0  0 58  0  1  0  0  0  0  0]
 [ 0  0  1  4  0  0  0  0  0  0 59  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 55  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0 64  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0 68  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56]]
==================================================
Model: Gaussian Naive Bayes
Accuracy: 0.3492063492063492
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.34      0.44        74
           1       0.52      0.59      0.55        71
           2       0.35      0.10      0.16        67
           3       0.59      0.24      0.34        68
           4       0.44      0.05      0.10        75
           5       0.33      0.15      0.20        48
           6       0.21      1.00      0.35        57
           7       0.85      0.80      0.83        51
           8       0.44      0.07      0.12        60
           9       0.65      0.39      0.49        61
          10       0.33      0.19      0.24        64
          11       0.43      0.11      0.17        57
          12       0.17      0.90      0.28        62
          13       0.76      0.32      0.45        68
          14       0.38      0.07      0.12        70
          15       0.71      0.39      0.50        62
          16       0.49      0.39      0.44        56

    accuracy                           0.35      1071
   macro avg       0.49      0.36      0.34      1071
weighted avg       0.49      0.35      0.33      1071

Confusion Matrix:
 [[25  3  0  0  1  0  6  0  0  3  0  0 23  0  0  2 11]
 [ 0 42  0  0  0  0  4  0  0  0  0  0 20  0  1  4  0]
 [ 0  0  7  0  0  0 34  0  0  0  7  1 15  0  3  0  0]
 [ 0  0  0 16  0  0 21  3  0  0  8  0 14  6  0  0  0]
 [ 0  2  1  2  4  4 23  1  2  6  3  1 20  0  3  0  3]
 [ 3  2  0  0  0  7 11  0  2  1  0  2 19  0  0  1  0]
 [ 0  0  0  0  0  0 57  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  6 41  0  0  0  0  1  1  0  0  0]
 [ 3  1  0  0  1  0 20  0  4  3  0  2 18  0  1  3  4]
 [ 0  3  1  0  0  3 10  0  0 24  0  1 17  0  0  0  2]
 [ 0  0  4  2  0  0 25  3  0  0 12  0 18  0  0  0  0]
 [ 1  3  3  0  1  5  5  0  1  0  4  6 26  0  0  0  2]
 [ 0  4  0  0  0  2  0  0  0  0  0  0 56  0  0  0  0]
 [ 0  0  0  5  0  0  9  0  0  0  0  0 32 22  0  0  0]
 [ 2  4  4  0  2  0 30  0  0  0  2  0 20  0  5  0  1]
 [ 0 12  0  0  0  0  0  0  0  0  0  1 25  0  0 24  0]
 [ 6  5  0  0  0  0 10  0  0  0  0  0 13  0  0  0 22]]
==================================================
Model: AdaBoost Classifier

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Accuracy: 0.21942110177404295
Classification Report:
               precision    recall  f1-score   support

           0       0.17      0.05      0.08        74
           1       1.00      0.48      0.65        71
           2       0.26      0.55      0.35        67
           3       0.00      0.00      0.00        68
           4       0.17      0.11      0.13        75
           5       0.12      0.77      0.21        48
           6       0.00      0.00      0.00        57
           7       0.19      1.00      0.32        51
           8       0.00      0.00      0.00        60
           9       0.17      0.25      0.20        61
          10       0.00      0.00      0.00        64
          11       0.00      0.00      0.00        57
          12       0.00      0.00      0.00        62
          13       0.00      0.00      0.00        68
          14       0.00      0.00      0.00        70
          15       0.28      0.13      0.18        62
          16       0.37      0.73      0.49        56

    accuracy                           0.22      1071
   macro avg       0.16      0.24      0.15      1071
weighted avg       0.17      0.22      0.15      1071

Confusion Matrix:
 [[ 4  0  0  0  0 40  0  0  0  0  0  0  0  0  0  8 22]
 [ 0 34  0  0  2 31  0  0  0  1  0  0  0  0  0  2  1]
 [ 0  0 37  0  0  0  0 10  0 16  0  0  0  0  1  0  3]
 [ 0  0  0  0  0  0  0 68  0  0  0  0  0  0  0  0  0]
 [ 7  0 12  0  8 20  0 12  0  7  0  0  0  0  1  2  6]
 [ 0  0  0  0  5 37  0  0  0  2  0  0  0  0  4  0  0]
 [ 0  0 28  0  0  1  0  0  0  6  0  0  0  0  7  0 15]
 [ 0  0  0  0  0  0  0 51  0  0  0  0  0  0  0  0  0]
 [ 2  0  7  0  5 25  0  0  0 10  0  0  0  0  2  1  8]
 [ 4  0  0  0 12 17  1  0  0 15  0  0  0  0  2  5  5]
 [ 0  0 24  0  0  0  0 40  0  0  0  0  0  0  0  0  0]
 [ 4  0 13  0  4 23  0  2  0 10  0  0  0  0  0  0  1]
 [ 1  0  4  0  6 35  0  0  0  8  0  0  0  0  6  2  0]
 [ 0  0  0  0  0  0  0 68  0  0  0  0  0  0  0  0  0]
 [ 2  0 15  0  3 18  0 15  0 11  0  0  0  0  0  1  5]
 [ 0  0  0  0  0 50  0  0  0  0  0  0  0  0  0  8  4]
 [ 0  0  2  0  2  9  0  0  0  0  0  0  0  0  2  0 41]]
==================================================
Model: Gradient Boosting Classifier
Accuracy: 0.876750700280112
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.97      0.93        74
           1       0.94      0.90      0.92        71
           2       0.86      0.96      0.91        67
           3       0.78      1.00      0.88        68
           4       0.92      0.44      0.59        75
           5       0.68      0.56      0.61        48
           6       0.86      1.00      0.93        57
           7       0.96      0.96      0.96        51
           8       0.77      0.67      0.71        60
           9       0.94      0.82      0.88        61
          10       0.89      0.80      0.84        64
          11       0.83      0.96      0.89        57
          12       0.87      1.00      0.93        62
          13       0.94      0.96      0.95        68
          14       0.96      0.93      0.94        70
          15       0.90      0.98      0.94        62
          16       0.88      1.00      0.93        56

    accuracy                           0.88      1071
   macro avg       0.88      0.88      0.87      1071
weighted avg       0.88      0.88      0.87      1071

Confusion Matrix:
 [[72  0  0  0  1  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 64  0  0  0  2  0  0  0  0  0  0  3  0  0  1  0]
 [ 0  0 64  1  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0 68  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  5  4 33  5  1  2  7  0  4  5  2  0  2  0  4]
 [ 3  1  1  0  1 27  2  0  4  3  0  1  1  0  1  2  1]
 [ 0  0  0  0  0  0 57  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 49  0  0  0  0  0  1  0  0  0]
 [ 1  1  1  0  1  1  5  0 40  0  0  2  1  0  0  4  3]
 [ 3  0  1  0  0  3  0  0  1 50  0  1  2  0  0  0  0]
 [ 0  0  2  8  0  0  0  0  0  0 51  0  0  3  0  0  0]
 [ 0  0  0  0  0  1  1  0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0 65  0  0  0]
 [ 0  1  0  2  0  0  0  0  0  0  0  2  0  0 65  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56]]

Selecting Best Model

In [21]:
model_rfc = RandomForestClassifier()

model_rfc.fit(X_train,y_train)

y_pred = model_rfc.predict(X_test)



print("confusion matrix \n: ", confusion_matrix(y_test,y_pred))
print("classification report \n: ", classification_report(y_test, y_pred))

confusion matrix
:  [[72  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 1 65  0  0  0  1  0  0  1  0  0  0  2  0  0  1  0]
 [ 0  0 66  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0 68  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  2 56  6  1  2  1  0  1  0  2  0  0  0  2]
 [ 2  1  0  0  3 37  0  0  2  0  0  1  2  0  0  0  0]
 [ 0  0  0  0  0  0 57  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0 48  0  0  0  0  0  1  0  0  0]
 [ 6  0  0  0  1  1  6  0 43  0  0  0  1  0  0  1  1]
 [ 0  0  0  0  0  2  0  0  0 59  0  0  0  0  0  0  0]
 [ 0  0  1  5  0  0  0  2  0  0 56  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0 65  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0 68  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56]]
classification report
:                precision    recall  f1-score   support

           0       0.89      0.97      0.93        74
           1       0.98      0.92      0.95        71
           2       0.96      0.99      0.97        67
           3       0.85      1.00      0.92        68
           4       0.89      0.75      0.81        75
           5       0.79      0.77      0.78        48
           6       0.89      1.00      0.94        57
           7       0.92      0.94      0.93        51
           8       0.91      0.72      0.80        60
           9       1.00      0.97      0.98        61
          10       0.97      0.88      0.92        64
          11       0.95      0.96      0.96        57
          12       0.89      1.00      0.94        62
          13       0.98      0.96      0.97        68
          14       1.00      0.97      0.99        70
          15       0.97      0.98      0.98        62
          16       0.93      1.00      0.97        56

    accuracy                           0.93      1071
   macro avg       0.93      0.93      0.93      1071
weighted avg       0.93      0.93      0.93      1071

In [22]:
import os
os.path.exists(r"C:\Users\Admin\Desktop\career aspiration")

False

In [23]:
os.path.exists(r"C:\Users\Admin\OneDrive\Desktop\career aspiration")

True

Saving Model, Encoder, Scaler for production

In [24]:

import pickle

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)

with open("model_rfc.pkl", "wb") as f:
    pickle.dump(model_rfc, f)

Prediction on new data

In [25]:
import pickle

encoder = pickle.load(open("encoder.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))
model_rfc = pickle.load(open("model_rfc.pkl", "rb"))

In [26]:
import joblib
joblib.dump(model_rfc, "model_rfc.pkl", compress=3)

['model_rfc.pkl']

In [27]:



career_aspiration_map = {
    0: 'Software Engineer',
    1: 'Business Owner',
    2: 'Unknown',
    3: 'Banker',
    4: 'Lawyer',
    5: 'Accountant',
    6: 'Doctor',
    7: 'Real Estate Developer',
    8: 'Stock Investor',
    9: 'Construction Engineer',
    10: 'Artist',
    11: 'Game Developer',
    12: 'Government Officer',
    13: 'Teacher',
    14: 'Designer',
    15: 'Scientist',
    16: 'Writer'
}


def predict_career(gender, part_time_job, absence_days, extracurricular_activities, weekly_self_study_hours,
                   math_score, history_score, physics_score, chemistry_score, biology_score, english_score,
                   geography_score, total_score):
    """
    This function will use the trained model to predict career aspiration
    based on the input data provided.
    """
    # Create a DataFrame with the input values
    input_data = pd.DataFrame([[gender, part_time_job, absence_days, extracurricular_activities,
                                weekly_self_study_hours, math_score, history_score, physics_score,
                                chemistry_score, biology_score, english_score, geography_score,
                                total_score]],
                              columns=['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
                                       'weekly_self_study_hours', 'math_score', 'history_score', 'physics_score',
                                       'chemistry_score', 'biology_score', 'english_score', 'geography_score',
                                       'total_score'])

    # Encode categorical features using the loaded encoder
    input_data['gender'] = encoder.transform(input_data['gender'])
    input_data['part_time_job'] = encoder.transform(input_data['part_time_job'])
    input_data['extracurricular_activities'] = encoder.transform(input_data['extracurricular_activities'])

    # Scale numerical features using the loaded scaler
    input_data[['absence_days', 'weekly_self_study_hours', 'math_score', 'history_score',
              'physics_score', 'chemistry_score', 'biology_score',
              'english_score', 'geography_score']] = scaler.transform(
        input_data[['absence_days', 'weekly_self_study_hours', 'math_score', 'history_score',
              'physics_score', 'chemistry_score', 'biology_score',
              'english_score', 'geography_score']])

    # Make prediction using the pre-trained model
    result = model_rfc.predict(input_data)
    career_aspiration = career_aspiration_map[result[0]]

    return career_aspiration

In [28]:
# Predefined values (you can modify these based on your needs)
gender = 'male'
part_time_job = 'True'
absence_days = 2
extracurricular_activities = 'False'
weekly_self_study_hours = 8
math_score = 87
history_score = 76
physics_score = 84
chemistry_score = 80
biology_score = 90
english_score = 85
geography_score = 78
total_score = 640  


# Predict career aspiration
predicted_career = predict_career(gender, part_time_job, absence_days, extracurricular_activities, 
                                  weekly_self_study_hours, math_score, history_score, physics_score,
                                  chemistry_score, biology_score, english_score, geography_score,
                                  total_score)

# Print the result
print(f"Predicted Career Aspiration: {predicted_career}")

Predicted Career Aspiration: Unknown